name: Publish QPM Package

env:
  module_id: tracks
  qmodName: Tracks
  cache-name: tracks_cache

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          submodules: true
          lfs: true

      - uses: seanmiddleditch/gha-setup-ninja@v3
      
      # - name: Create ndkpath.txt
      #   run: |
      #     echo "$ANDROID_NDK_LATEST_HOME" > ${GITHUB_WORKSPACE}/ndkpath.txt
      #     cat ${GITHUB_WORKSPACE}/ndkpath.txt

      - name: Get Tag Version
        id: get_tag_version
        run: |
          echo ${GITHUB_REF#refs/tags/}
          echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: QPM Rust Action
        uses: Fernthedev/qpm-action@v1
        with:
          #required
          workflow_token: ${{secrets.GITHUB_TOKEN}}

          restore: true # will run restore on download
          cache: true #will cache dependencies

          publish: "late"
          publish_token: ${{secrets.QPM_TOKEN}}

          version: ${{ steps.get_tag_version.outputs.VERSION }}
          tag: ${{ steps.get_tag_version.outputs.TAG }}

          # set to true if applicable, ASSUMES the file is already a release asset
          qpm_release_bin: true
          qpm_debug_bin: true

          # Name of qmod in release asset. Assumes exists, same as prior
          qpm_qmod: ${{env.qmodName}}.qmod

      - name: Setup Rust
        run: |
          rustup install nightly
          rustup target add aarch64-linux-android --toolchain nightly
          cargo install --locked --git https://github.com/bbqsrc/cargo-ndk.git cargo-ndk

      - name: Build
        run: |
          cd ${GITHUB_WORKSPACE}
          qpm s build
          qpm qmod zip

      - name: Get Library Name
        id: libname
        run: |
          cd ./build/
          pattern="lib${module_id}*.so"
          files=( $pattern )
          echo ::set-output name=NAME::"${files[0]}"

      - name: Rename debug
        run: |
          mv ./build/debug/${{ steps.libname.outputs.NAME }} ./build/debug/debug_${{ steps.libname.outputs.NAME }}


      - name: Upload to Release
        id: upload_file_release
        uses: softprops/action-gh-release@v0.1.15
        with:
          name: ${{ github.event.inputs.release_msg }}
          tag_name: ${{ github.event.inputs.version }}
          files: |
            ./${{ env.qmodName }}.qmod
            ./build/${{ steps.libname.outputs.NAME }}
            ./build/debug/debug_${{ steps.libname.outputs.NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Make PR to QeatMods3
        id: qmod-release
        uses: QuestPackageManager/qmod-repo-publish-action@main
        # TODO: Make this work!
        continue-on-error: true
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          # first asset URL
          qmod_url: ${{ fromJSON(steps.upload_file_release.outputs.assets)[0].browser_download_url }}
          qmod_repo_owner: 'dantheman827'
          qmod_repo_name: 'bsqmods'